"""tambah kolom deskripsi

Revision ID: 3e1786f7ce7f
Revises: 6e28be1c2cf3
Create Date: 2026-03-03 18:41:27.671054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1786f7ce7f'
down_revision: Union[str, Sequence[str], None] = '6e28be1c2cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('deskripsi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produk', 'deskripsi')
    # ### end Alembic commands ###
